[2024-09-24T14:58:01.130+0000] {processor.py:161} INFO - Started process (PID=1644) to work on /opt/airflow/dags/dag1.py
[2024-09-24T14:58:01.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-09-24T14:58:01.135+0000] {logging_mixin.py:188} INFO - [2024-09-24T14:58:01.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-09-24T14:58:01.142+0000] {logging_mixin.py:188} INFO - [2024-09-24T14:58:01.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2024-09-24T14:58:01.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-09-24T14:58:01.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.042 seconds
[2024-09-24T14:58:31.588+0000] {processor.py:161} INFO - Started process (PID=1649) to work on /opt/airflow/dags/dag1.py
[2024-09-24T14:58:31.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-09-24T14:58:31.591+0000] {logging_mixin.py:188} INFO - [2024-09-24T14:58:31.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-09-24T14:58:31.600+0000] {logging_mixin.py:188} INFO - [2024-09-24T14:58:31.599+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2024-09-24T14:58:31.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-09-24T14:58:31.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.038 seconds
[2024-09-24T14:59:02.019+0000] {processor.py:161} INFO - Started process (PID=1662) to work on /opt/airflow/dags/dag1.py
[2024-09-24T14:59:02.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-09-24T14:59:02.022+0000] {logging_mixin.py:188} INFO - [2024-09-24T14:59:02.022+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-09-24T14:59:02.030+0000] {logging_mixin.py:188} INFO - [2024-09-24T14:59:02.029+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2024-09-24T14:59:02.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-09-24T14:59:02.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.035 seconds
[2024-09-24T14:59:32.522+0000] {processor.py:161} INFO - Started process (PID=1667) to work on /opt/airflow/dags/dag1.py
[2024-09-24T14:59:32.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag1.py for tasks to queue
[2024-09-24T14:59:32.526+0000] {logging_mixin.py:188} INFO - [2024-09-24T14:59:32.525+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag1.py
[2024-09-24T14:59:32.534+0000] {logging_mixin.py:188} INFO - [2024-09-24T14:59:32.533+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag1.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2024-09-24T14:59:32.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag1.py
[2024-09-24T14:59:32.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag1.py took 0.043 seconds
